sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake
      - cmake-data
      - libboost-dev
      - libboost-program-options-dev
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - export ROOT_TRAVIS_DIR=$(pwd)
  - cd $ROOT_TRAVIS_DIR
install:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
script:
  - make check
